package ch.screenconcept.artoz.website.hmc;

/*
The extension "website" is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

import de.hybris.platform.hmc.webchips.*;

import java.util.Map;
import org.apache.log4j.Logger;

public class WebsiteContentChip extends AbstractChip
{
	//Log4J implementation - edit project.properties file's Logging section to configurate your own log channel
	static final Logger log = Logger.getLogger( WebsiteContentChip.class.getName() );
	
	public WebsiteContentChip(DisplayState displayState, Chip parent)
	{
		super(displayState, parent);
	}
			
	/**
	 * @see de.hybris.platform.hmc.webchips.Chip#processEvents(Map)
	 */
	public void processEvents(Map events)
	{
	}
	
	/**
	 * @see de.hybris.platform.hmc.webchips.Chip#getJSPURI()
	 */
	public String getJSPURI()
	{
		return "/ext/website/WebsiteContentChip.jsp";
	}
	
	/**
	 * Test method generated by ExtGen
	 */
	public boolean isTestOK()
	{
		return true;
	}
}