/*
 * Generated by ExtGen v3.0 
 */
package ch.screenconcept.artoz.website.constants;



/**
 * Global class for all Website constants.  
 * You can add global constants for your extension into this class 
 */
public final class WebsiteConstants extends GeneratedWebsiteConstants
{	
}
