/*
 * Generated by ExtGen v3.0 
 */
package ch.screenconcept.artoz.website.constants;

/**
 * Global class for all Website constants. You can add global constants for your
 * extension into this class
 */
public final class WebsiteConstants extends GeneratedWebsiteConstants
{
	/** URL Parameter: page */
	public static final String PARAM_PAGEID = "pageid";

	public static final String MAIN_NAV = "main_nav";
	
	public static final String HELP_NAV = "help_nav";
	
	public static final String QUICK_NAV = "quick_nav";
	
	public static final String LEXIKON = "lexikon";
	
	public static final String PARAM_PARTICIPATION = "partid";

}
