/*
 * Generated by ExtGen v3.0 
 */
package ch.screenconcept.artoz.website.jalo;

import org.apache.log4j.Logger;

import de.hybris.platform.testframework.JaloTest;

/**
 * JUnit Tests for the Website extension
 */

public class WebsiteTest extends JaloTest
{
	/*
	 * edit the local|project.properties to change logging behaviour (properties
	 * log4j.*)
	 */
	@SuppressWarnings("unused")
	private static final Logger log = Logger.getLogger(WebsiteTest.class.getName());

	public WebsiteTest(String name)
	{
		super(name);
	}

	@Override
	protected void setUp() throws Exception
	{
		super.setUp();
	}

	@Override
	protected void tearDown() throws Exception
	{
		super.tearDown();
	}

	/**
	 * this is a sample test method
	 */
	public void testWebsite()
	{
		assertTrue(true);
	}

}
