

package website;

import java.util.*;
import java.io.Serializable;
import de.hybris.platform.util.*;
import de.hybris.platform.core.*;
import de.hybris.platform.jalo.JaloBusinessException;
import de.hybris.platform.jalo.type.*;
import de.hybris.platform.jalo.type.AttributeDescriptor;
import de.hybris.platform.jalo.type.CollectionType;
import de.hybris.platform.persistence.type.*;
import de.hybris.platform.persistence.enumeration.*;
import de.hybris.platform.persistence.property.PersistenceManager;
import de.hybris.platform.persistence.*;
		
public class GeneratedTypeInitializer extends AbstractTypeInitializer
{
	public GeneratedTypeInitializer( ManagerEJB manager, Map params )
	{
		super( manager, params );
	}


	/**
	 * generated by hybris E-Business Platform
	 */
	protected void performRemoveObjects( ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// no-op by now
	}

	/**
	 * generated by hybris E-Business Platform
	 */
	protected final void performCreateTypes( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
					
	
	}
			
	/**
	 * generated by hybris E-Business Platform
	 */
	protected final void performModifyTypes( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{

	

	

	}
	
	
	
	
		
			
	/**
	 * generated by hybris E-Business Platform
	 */
	protected final void performCreateObjects( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		Map customPropsMap = null;

	
	
	}
	

		
}

	