/*
 * Generated by ExtGen v3.0 
 */
package ch.screenconcept.artoz.website;

import org.apache.log4j.Logger;


/**
 * simple test class to demonstrate how to include utility classes to your webmodule
 */
public class WebsiteWebHelper
{
	/* edit the local|project.properties to change logging behaviour (properties log4j.*) */
	@SuppressWarnings("unused")
	private static final Logger log = Logger.getLogger( WebsiteWebHelper.class.getName() );
	
	
	public static final String getTestOutput()
	{
		return "testoutput";
	}
	
}

