/*
 * Generated by ExtGen v3.0 
 */
package ch.screenconcept.artoz.constants;



/**
 * Global class for all Artoz constants.  
 * You can add global constants for your extension into this class 
 */
public final class ArtozConstants extends GeneratedArtozConstants
{	
}
