<%@include file="../../head.inc"%>
<%@page import="ch.screenconcept.artoz.hmc.ArtozContentChip"%>

<%
	ArtozContentChip theChip = (ArtozContentChip) request.getAttribute( AbstractChip.CHIP_KEY );
%>

<table style="background-image: url( images/alpha.png )" width="100%" style="height:100%;">
	<tr>
		<td>
			<table width="100%">
				<tr>
					<td class="sectionheader">artoz, generated by extGen.</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td>
			<table cellspacing="0" cellpadding="20" width="100%" height="10px">
				<tr nowrap>
					<td width="100%">
						This is an example for a generated ContentChip.
						<p>
						Current User: <%= JaloSession.getCurrentSession().getUser().getLogin() %>
						<p>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
