/*
 * Generated by ExtGen v3.0 
 */
package ch.screenconcept.artoz.website;

import de.hybris.platform.core.Registry;
import de.hybris.platform.jalo.JaloSession;
import de.hybris.platform.util.Utilities;

/** 
 * demonstration of how to write a standalone application that can be run directly 
 * from within eclipse or from the commandline
 * 
 * To run this from commandline, just use the following command:
 * <code>
 * java -jar bootstrap/bin/ybootstrap.jar "new ch.screenconcept.artoz.website.WebsiteStandalone().run();"
 * </code>
 * 
 * From eclipse, just run as Java Application. Note that you maybe need to add all
 * other projects like ext-commerce, ext-pim to the Launch configuration classpath.
 */ 

public class WebsiteStandalone
{
	
	/**
	 * main class to be able to run it directly as a java program
	 * @param args the arguments from commandline
	 */
	public static void main( String[] args ) throws Exception
	{
		new WebsiteStandalone().run();
	}
	

	
	public void run() throws Exception
	{
		Registry.setPreferredClusterID(15);
		
		JaloSession jaloSession = JaloSession.getCurrentSession();
		System.out.println("Session ID: "+jaloSession.getSessionID());
		System.out.println("User: "+jaloSession.getUser());
		Utilities.printAppInfo();

	}
}
